steps:
  - id: publish
    name: gcr.io/cloud-builders/mvn
    args:
      - compile
      - jib:build
  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - demo-application
      - '--set-env-vars'
      - 'spring.profiles.active=caching'
      - '--set-env-vars'
      - 'spring.redis.host=${_REDIS_INSTANCE_IP}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/posts-demo-application'
      - '--region'
      - 'us-west1'
      - '--vpc-connector'
      - '${_VPC_CONNECTOR}'
substitutions:
  _REDIS_INSTANCE_IP: 10.72.225.3
  _VPC_CONNECTOR: cloud-run
